require('dotenv').config({ path: require('path').join(__dirname, '..', '.env') });
const mongoose = require('mongoose');
const Finance = require('../modules/finance/model');

function parseAmount(value) {
  if (value == null || value === '') return 0;
  const cleaned = String(value).replace(/[₹,\s]/g, '');
  if (cleaned === '' || /^N\/A$/i.test(cleaned) || /^Varies$/i.test(cleaned)) return 0;
  const match = cleaned.match(/^0*(\d+)/);
  if (!match) return 0;
  const num = parseFloat(match[1]);
  return isNaN(num) ? 0 : num;
}

function parseInterest(value) {
  if (value == null || value === '') return { min: 0, max: 0 };
  const cleaned = String(value).replace(/%/g, '').trim();
  if (/^N\/A$/i.test(cleaned) || /^Varies$/i.test(cleaned)) return { min: 0, max: 0 };
  const parts = cleaned.split(/[–-]/).map((p) => parseFloat(p.trim()));
  const nums = parts.filter((n) => !isNaN(n));
  if (nums.length === 0) return { min: 0, max: 0 };
  return { min: nums[0], max: nums.length > 1 ? nums[nums.length - 1] : nums[0] };
}

const base = {
  city: 'bengaluru',
  status: 'active',
  featured: false,
};

const services = [
  {
    ...base,
    serviceName: 'Home Loan – HDFC Ltd.',
    category: 'Home Loans',
    companyName: 'HDFC Ltd.',
    providerType: 'Bank',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/HDFC_Logo.svg/1200px-HDFC_Logo.svg.png',
    banner: 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1600',
    interestRate: '7% – 8.5%',
    minAmount: '₹5,00,000',
    maxAmount: '₹5,00,00,000',
    tenure: 'Up to 30 years',
    description: 'Comprehensive home loan solutions for buying, constructing, or renovating your dream home. Competitive interest rates with minimal documentation and quick disbursal.',
    eligibility: ['Salaried / Self-employed individuals', 'Age: 21 – 65 years', 'Min income: ₹25,000/month', 'CIBIL: 650+'],
    documentsRequired: ['Aadhaar Card', 'PAN Card', 'Income Proof (6 months)', 'Bank Statements (6 months)', 'Property Documents'],
    processingTime: '3 – 7 working days',
    features: ['100% financing available', 'Flexible EMI options', 'No hidden charges', 'Top-up loan facility', 'Balance transfer option'],
    area: 'Indiranagar',
    pincode: '560038',
    contactPhone: '9876543210',
    contactEmail: 'homeloans@hdfc.example.com',
    serviceMode: 'Both',
    postedBy: 'Bank',
    availability: 'Available Now',
    featured: true,
  },
  {
    ...base,
    serviceName: 'Instant Personal Loan',
    category: 'Personal Loans',
    companyName: 'ICICI Bank',
    providerType: 'Bank',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/ICICI_Bank_Logo.svg/1200px-ICICI_Bank_Logo.svg.png',
    banner: 'https://images.pexels.com/photos/4386366/pexels-photo-4386366.jpeg?auto=compress&cs=tinysrgb&w=1600',
    interestRate: '10.5% – 24%',
    minAmount: '₹50,000',
    maxAmount: '₹50,00,000',
    tenure: '1 – 5 years',
    description: 'Get instant personal loans with zero collateral and minimal documentation. Funds credited within 24 hours of approval.',
    eligibility: ['Salaried individuals', 'Age: 23 – 58 years', 'Min income: ₹20,000/month', 'CIBIL: 700+'],
    documentsRequired: ['Aadhaar Card', 'PAN Card', 'Salary Slips (3 months)', 'Bank Statements (3 months)'],
    processingTime: 'Same day – 24 hours',
    features: ['Zero collateral', 'Same-day disbursal', 'Flexible tenure', 'Part-prepayment allowed', 'No end-use restriction'],
    area: 'Koramangala',
    pincode: '560034',
    contactPhone: '9876543211',
    contactEmail: 'personalloans@icici.example.com',
    serviceMode: 'Both',
    postedBy: 'Bank',
    availability: 'Available Now',
    featured: true,
  },
  {
    ...base,
    serviceName: 'Two-Wheeler & Car Loan',
    category: 'Vehicle Loans',
    companyName: 'Bajaj Finserv',
    providerType: 'NBFC',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Bajaj_Finserv_logo.svg/1200px-Bajaj_Finserv_logo.svg.png',
    banner: 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&w=1600',
    interestRate: '8% – 15%',
    minAmount: '₹50,000',
    maxAmount: '₹2,00,00,000',
    tenure: '1 – 7 years',
    description: 'Financing for new and pre-owned vehicles including two-wheelers, cars, and commercial vehicles. Quick approval with minimal documentation.',
    eligibility: ['Salaried / Self-employed', 'Age: 21 – 60 years', 'Min income: ₹15,000/month', 'CIBIL: 600+'],
    documentsRequired: ['Aadhaar Card', 'PAN Card', 'Income Proof', 'Vehicle Quotation', 'Bank Statements'],
    processingTime: '24 – 48 hours',
    features: ['New & used vehicle financing', 'Zero down payment options', 'Insurance bundled', 'Quick disbursal', 'Part exchange facility'],
    area: 'Whitefield',
    pincode: '560066',
    contactPhone: '9876543212',
    contactEmail: 'vehicle@bajajfinserv.example.com',
    serviceMode: 'Both',
    postedBy: 'Agent',
    availability: 'Available Now',
    featured: true,
  },
  {
    ...base,
    serviceName: 'Business Loan – Mudra & MSME',
    category: 'Business Loans',
    companyName: 'State Bank of India',
    providerType: 'Bank',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/State_Bank_of_India_logo.svg/1200px-State_Bank_of_India_logo.svg.png',
    banner: 'https://images.pexels.com/photos/5648102/pexels-photo-5648102.jpeg?auto=compress&cs=tinysrgb&w=1600',
    interestRate: '9% – 14%',
    minAmount: '₹1,00,000',
    maxAmount: '₹2,00,00,000',
    tenure: '1 – 10 years',
    description: 'Business loans under Mudra Yojana and MSME schemes for startups, working capital, and business expansion. Government-backed schemes available.',
    eligibility: ['Business owner / Proprietor', 'Business vintage: 1+ years', 'ITR filed for 1+ years', 'CIBIL: 650+'],
    documentsRequired: ['Aadhaar Card', 'PAN Card', 'Business Proof', 'ITR (2 years)', 'Bank Statements (6 months)', 'GST Returns'],
    processingTime: '5 – 10 working days',
    features: ['Government-backed schemes', 'Collateral-free up to ₹10L', 'Flexible repayment', 'Working capital & term loan', 'Export finance available'],
    area: 'MG Road',
    pincode: '560001',
    contactPhone: '9876543213',
    contactEmail: 'business@sbi.example.com',
    serviceMode: 'Both',
    postedBy: 'Bank',
    availability: 'Available Now',
    featured: true,
  },
  {
    ...base,
    serviceName: 'Gold Loan – Instant Cash',
    category: 'Gold Loans',
    companyName: 'Muthoot Finance',
    providerType: 'NBFC',
    logo: '',
    banner: 'https://images.pexels.com/photos/264548/pexels-photo-264548.jpeg?auto=compress&cs=tinysrgb&w=1600',
    interestRate: '7% – 18%',
    minAmount: '₹5,000',
    maxAmount: '₹2,00,00,000',
    tenure: '3 months – 3 years',
    description: 'Instant gold loans against gold ornaments and coins. High loan-to-value ratio with transparent valuation and secure storage.',
    eligibility: ['Individuals above 18 years', 'Valid ID proof', 'Gold ornaments / coins'],
    documentsRequired: ['Aadhaar Card', 'PAN Card', 'Gold Ornaments'],
    processingTime: '15 – 30 minutes',
    features: ['High LTV up to 75%', 'No income proof required', 'Instant disbursal', 'Safe custody', 'Flexible repayment options'],
    area: 'JP Nagar',
    pincode: '560078',
    contactPhone: '9876543214',
    contactEmail: 'goldloan@muthoot.example.com',
    serviceMode: 'Offline',
    postedBy: 'Agent',
    availability: 'Available Now',
  },
  {
    ...base,
    serviceName: 'Education Loan – Study Abroad & India',
    category: 'Education Loans',
    companyName: 'Axis Bank',
    providerType: 'Bank',
    logo: '',
    banner: 'https://images.pexels.com/photos/301920/pexels-photo-301920.jpeg?auto=compress&cs=tinysrgb&w=1600',
    interestRate: '9% – 13%',
    minAmount: '₹2,00,000',
    maxAmount: '₹1,50,00,000',
    tenure: '5 – 15 years',
    description: 'Education loans for undergraduate, postgraduate, and doctoral studies in India and abroad. Covers tuition, living expenses, and travel.',
    eligibility: ['Student age: 18 – 35 years', 'Admission to recognized institution', 'Co-applicant required', 'Indian resident'],
    documentsRequired: ['Admission Letter', 'Fee Structure', 'Student KYC', 'Co-applicant KYC', 'Co-applicant Income Proof'],
    processingTime: '7 – 15 working days',
    features: ['Loan up to ₹1.5 Cr', 'Moratorium period available', 'No collateral up to ₹7.5L', 'Tax benefits under Sec 80E', 'Quick online process'],
    area: 'Jayanagar',
    pincode: '560011',
    contactPhone: '9876543215',
    contactEmail: 'education@axis.example.com',
    serviceMode: 'Both',
    postedBy: 'Financial Consultant',
    availability: 'Appointment Required',
  },
  {
    ...base,
    serviceName: 'Life & Term Insurance Plans',
    category: 'Insurance',
    companyName: 'LIC of India',
    providerType: 'Financial Institution',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/85/LIC_Logo.svg/1200px-LIC_Logo.svg.png',
    banner: 'https://images.pexels.com/photos/40568/medical-appointment-doctor-health-40568.jpeg?auto=compress&cs=tinysrgb&w=1600',
    interestRate: 'N/A',
    minAmount: '₹5,00,000',
    maxAmount: '₹1,00,00,000',
    tenure: '10 – 30 years',
    description: 'Comprehensive life insurance and term plans with guaranteed returns, critical illness cover, and family protection options.',
    eligibility: ['Age: 18 – 65 years', 'Indian resident', 'Medical checkup may be required'],
    documentsRequired: ['Aadhaar Card', 'PAN Card', 'Address Proof', 'Medical Reports (if applicable)'],
    processingTime: '2 – 5 working days',
    features: ['Tax benefits under Sec 80C & 10D', 'Critical illness cover', 'Maturity benefits', 'Loan against policy', 'Family rider options'],
    area: 'Vijayanagar',
    pincode: '560040',
    contactPhone: '9876543216',
    contactEmail: 'insurance@lic.example.com',
    serviceMode: 'Both',
    postedBy: 'Financial Consultant',
    availability: 'Available Now',
  },
  {
    ...base,
    serviceName: 'Wealth Management & Investment Advisory',
    category: 'Investment Services',
    companyName: 'Zerodha Securities',
    providerType: 'Financial Institution',
    logo: '',
    banner: 'https://images.pexels.com/photos/5830672/pexels-photo-5830672.jpeg?auto=compress&cs=tinysrgb&w=1600',
    interestRate: 'Varies',
    minAmount: '₹1,00,000',
    maxAmount: '₹5,00,00,000',
    tenure: 'Flexible',
    description: 'Professional wealth management and investment advisory services including mutual funds, stocks, bonds, and portfolio management.',
    eligibility: ['Indian resident / NRI', 'Min investment: ₹1L', 'KYC compliant'],
    documentsRequired: ['PAN Card', 'Aadhaar Card', 'Bank Details', 'Signature Proof'],
    processingTime: '1 – 3 working days',
    features: ['Expert wealth management', 'Diversified portfolio', 'Regular portfolio review', 'Tax planning', 'Retirement planning'],
    area: 'HSR Layout',
    pincode: '560102',
    contactPhone: '9876543217',
    contactEmail: 'wealth@zerodha.example.com',
    serviceMode: 'Both',
    postedBy: 'Financial Consultant',
    availability: 'Appointment Required',
  },
  {
    ...base,
    serviceName: 'Platinum Credit Card & Premium Banking',
    category: 'Credit Cards',
    companyName: 'HDFC Bank',
    providerType: 'Bank',
    logo: '',
    banner: 'https://images.pexels.com/photos/4467735/pexels-photo-4467735.jpeg?auto=compress&cs=tinysrgb&w=1600',
    interestRate: '12% – 42%',
    minAmount: '₹50,000',
    maxAmount: '₹25,00,000',
    tenure: 'Revolving',
    description: 'Premium credit cards with travel rewards, cashback, lounge access, and concierge services. Exclusive banking benefits.',
    eligibility: ['Salaried / Self-employed', 'Min income: ₹8L/year', 'CIBIL: 750+', 'Age: 21 – 60 years'],
    documentsRequired: ['PAN Card', 'Aadhaar Card', 'Income Proof', 'Bank Statements (3 months)'],
    processingTime: '3 – 7 working days',
    features: ['Complimentary lounge access', 'Reward points on every spend', 'Fuel surcharge waiver', 'Zero liability on loss', 'EMI conversion facility'],
    area: 'MG Road',
    pincode: '560001',
    contactPhone: '9876543218',
    contactEmail: 'cards@hdfcbank.example.com',
    serviceMode: 'Both',
    postedBy: 'Bank',
    availability: 'Available Now',
  },
  {
    ...base,
    serviceName: 'Personalised Financial Planning',
    category: 'Financial Advisors',
    companyName: 'Vishwam Wealth Desk',
    providerType: 'Individual Consultant',
    logo: '',
    banner: 'https://images.pexels.com/photos/3831645/pexels-photo-3831645.jpeg?auto=compress&cs=tinysrgb&w=1600',
    interestRate: 'N/A',
    minAmount: '₹50,000',
    maxAmount: '₹2,00,00,000',
    tenure: 'As per plan',
    description: 'Independent financial advisory services including retirement planning, tax planning, investment strategy, and debt management.',
    eligibility: ['Any individual seeking financial guidance'],
    documentsRequired: ['KYC Documents', 'Financial Goals Statement', 'Existing Portfolio (if any)'],
    processingTime: '1 – 2 working days for consultation',
    features: ['Personalized financial plan', 'Goal-based investing', 'Tax optimization', 'Retirement planning', 'Regular portfolio review'],
    area: 'BTM Layout',
    pincode: '560029',
    contactPhone: '9876543219',
    contactEmail: 'advisory@vishwam.example.com',
    serviceMode: 'Both',
    postedBy: 'Financial Consultant',
    availability: 'Appointment Required',
    featured: true,
  },
  {
    ...base,
    serviceName: 'Construction Loan – Stage-Wise Disbursal',
    category: 'Home Loans',
    companyName: 'Tata Capital',
    providerType: 'NBFC',
    logo: '',
    banner: 'https://images.pexels.com/photos/159306/construction-site-build-construction-work-159306.jpeg?auto=compress&cs=tinysrgb&w=1600',
    interestRate: '9% – 11%',
    minAmount: '₹10,00,000',
    maxAmount: '₹3,00,00,000',
    tenure: '5 – 25 years',
    description: 'Construction loans with stage-wise disbursement linked to construction progress. Flexible repayment during construction phase.',
    eligibility: ['Property owner / Land owner', 'Valid building plan approval', 'CIBIL: 650+', 'Age: 21 – 65 years'],
    documentsRequired: ['Land Title Deed', 'Approved Building Plan', 'Cost Estimation', 'KYC Documents', 'Income Proof'],
    processingTime: '7 – 14 working days',
    features: ['Stage-wise disbursal', 'Interest-only during construction', 'Flexible repayment', 'No prepayment charges', 'Technical valuation included'],
    area: 'Sarjapur Road',
    pincode: '560035',
    contactPhone: '9876543220',
    contactEmail: 'construction@tatacapital.example.com',
    serviceMode: 'Both',
    postedBy: 'Bank',
    availability: 'Available Now',
  },
  {
    ...base,
    serviceName: 'Study Abroad Education Loan',
    category: 'Education Loans',
    companyName: 'HDFC Credila',
    providerType: 'NBFC',
    logo: '',
    banner: 'https://images.pexels.com/photos/207691/pexels-photo-207691.jpeg?auto=compress&cs=tinysrgb&w=1600',
    interestRate: '11% – 14%',
    minAmount: '₹5,00,000',
    maxAmount: '₹1,00,00,000',
    tenure: '5 – 15 years',
    description: 'Specialized education loans for studying abroad covering tuition, accommodation, travel, and living expenses with flexible repayment options.',
    eligibility: ['Admission to foreign university', 'Co-applicant with good credit', 'Course duration: 1+ years'],
    documentsRequired: ['University Admission Letter', 'Fee Structure', 'Student KYC', 'Co-applicant KYC & Income Proof', 'Visa Documents'],
    processingTime: '7 – 14 working days',
    features: ['Loan up to ₹1 Cr', 'Moratorium till course + 6 months', 'No collateral up to ₹7.5L', 'Quick online process', 'Dedicated counselor'],
    area: 'Malleshwaram',
    pincode: '560003',
    contactPhone: '9876543221',
    contactEmail: 'studyabroad@credila.example.com',
    serviceMode: 'Online',
    postedBy: 'Financial Consultant',
    availability: 'Appointment Required',
  },
  {
    ...base,
    serviceName: 'Health & Critical Illness Insurance',
    category: 'Insurance',
    companyName: 'HDFC Ergo',
    providerType: 'Financial Institution',
    logo: '',
    banner: 'https://images.pexels.com/photos/3735769/pexels-photo-3735769.jpeg?auto=compress&cs=tinysrgb&w=1600',
    interestRate: 'N/A',
    minAmount: '₹3,00,000',
    maxAmount: '₹50,00,000',
    tenure: '1 – 20 years',
    description: 'Health insurance plans with critical illness cover, hospitalization benefits, and wellness programs. Family floater options available.',
    eligibility: ['Age: 18 – 65 years', 'Indian resident', 'Medical underwriting required'],
    documentsRequired: ['Aadhaar Card', 'PAN Card', 'Medical History', 'Address Proof'],
    processingTime: '3 – 7 working days',
    features: ['Critical illness cover', 'Cashless hospitalization', 'Annual health checkup', 'Tax benefits under Sec 80D', 'Family floater option'],
    area: 'Rajajinagar',
    pincode: '560010',
    contactPhone: '9876543222',
    contactEmail: 'health@hdfcergo.example.com',
    serviceMode: 'Both',
    postedBy: 'Agent',
    availability: 'Available Now',
  },
  {
    ...base,
    serviceName: 'Used Car Loan',
    category: 'Vehicle Loans',
    companyName: 'Yes Bank',
    providerType: 'Bank',
    logo: '',
    banner: 'https://images.pexels.com/photos/1545743/pexels-photo-1545743.jpeg?auto=compress&cs=tinysrgb&w=1600',
    interestRate: '11% – 16%',
    minAmount: '₹1,00,000',
    maxAmount: '₹50,00,000',
    tenure: '1 – 5 years',
    description: 'Financing for pre-owned cars from authorized dealers and private sellers. Attractive interest rates with flexible tenure options.',
    eligibility: ['Age: 21 – 60 years', 'Min income: ₹20,000/month', 'CIBIL: 650+'],
    documentsRequired: ['KYC Documents', 'Income Proof', 'RC of Vehicle', 'Insurance Documents', 'Bank Statements'],
    processingTime: '24 – 48 hours',
    features: ['Loan for used cars up to 10 years old', 'Quick approval', 'Flexible tenure', 'Part-prepayment allowed', 'Insurance bundled'],
    area: 'Yelahanka',
    pincode: '560064',
    contactPhone: '9876543223',
    contactEmail: 'usedcar@yesbank.example.com',
    serviceMode: 'Both',
    postedBy: 'Bank',
    availability: 'Available Now',
  },
  {
    ...base,
    serviceName: 'Retirement Planning & Pension Advisory',
    category: 'Financial Advisors',
    companyName: 'SBI Mutual Fund',
    providerType: 'Financial Institution',
    logo: '',
    banner: 'https://images.pexels.com/photos/7412114/pexels-photo-7412114.jpeg?auto=compress&cs=tinysrgb&w=1600',
    interestRate: 'N/A',
    minAmount: '₹2,00,000',
    maxAmount: '₹5,00,00,000',
    tenure: '5 – 30 years',
    description: 'Comprehensive retirement planning services including pension plans, annuity options, and wealth preservation strategies for a secure post-retirement life.',
    eligibility: ['Age: 25 – 55 years', 'Regular income source', 'Long-term financial goals'],
    documentsRequired: ['KYC Documents', 'Income Proof', 'Existing Investment Details', 'Retirement Goal Statement'],
    processingTime: '3 – 5 working days for plan creation',
    features: ['Customized retirement plan', 'Pension & annuity options', 'Tax-efficient investing', 'Regular portfolio rebalancing', 'Estate planning'],
    area: 'Basavanagudi',
    pincode: '560004',
    contactPhone: '9876543224',
    contactEmail: 'retirement@sbimf.example.com',
    serviceMode: 'Both',
    postedBy: 'Financial Consultant',
    availability: 'Appointment Required',
  },
  {
    ...base,
    serviceName: 'Gold Loan – Doorstep Service',
    category: 'Gold Loans',
    companyName: 'Manappuram Finance',
    providerType: 'NBFC',
    logo: '',
    banner: 'https://images.pexels.com/photos/694740/pexels-photo-694740.jpeg?auto=compress&cs=tinysrgb&w=1600',
    interestRate: '6% – 16%',
    minAmount: '₹1,000',
    maxAmount: '₹1,00,00,000',
    tenure: '1 month – 3 years',
    description: 'Doorstep gold loan service with free valuation and instant cash disbursal. Transparent process with secure gold storage.',
    eligibility: ['Individuals above 18 years', 'Valid ID proof', 'Gold ornaments / coins / bars'],
    documentsRequired: ['Aadhaar Card', 'PAN Card'],
    processingTime: '10 – 20 minutes',
    features: ['Doorstep service', 'Free valuation', 'Instant cash disbursal', 'Lowest interest rates', 'Flexible repayment'],
    area: 'Banashankari',
    pincode: '560050',
    contactPhone: '9876543225',
    contactEmail: 'gold@manappuram.example.com',
    serviceMode: 'Both',
    postedBy: 'Agent',
    availability: 'Available Now',
  },
  {
    ...base,
    serviceName: 'Stock Trading & Investment Platform',
    category: 'Investment Services',
    companyName: 'Groww',
    providerType: 'Financial Institution',
    logo: '',
    banner: 'https://images.pexels.com/photos/6802048/pexels-photo-6802048.jpeg?auto=compress&cs=tinysrgb&w=1600',
    interestRate: 'N/A',
    minAmount: '₹0',
    maxAmount: 'No limit',
    tenure: 'N/A',
    description: 'India\'s largest stock broking platform with zero brokerage on equity delivery. Trade stocks, F&O, mutual funds, and bonds.',
    eligibility: ['Indian resident', '18+ years', 'KYC compliant', 'Valid bank account'],
    documentsRequired: ['PAN Card', 'Aadhaar Card', 'Bank Account', 'Signature Proof'],
    processingTime: '1 – 2 working days for account opening',
    features: ['Zero brokerage on delivery', 'Free account opening', 'Advanced trading platforms', 'Margin trading facility', 'Research reports'],
    area: 'Hebbal',
    pincode: '560024',
    contactPhone: '9876543226',
    contactEmail: 'invest@groww.example.com',
    serviceMode: 'Online',
    postedBy: 'Bank',
    availability: 'Available Now',
    featured: true,
  },
];

async function seed() {
  try {
    const uri = process.env.MONGODB_URI || 'mongodb://localhost:27017/onevishwam';
    await mongoose.connect(uri);
    console.log('Connected to MongoDB');

    await Finance.deleteMany({});
    console.log('Cleared existing finance services');

    const created = [];
    for (const data of services) {
      const { min, max } = parseInterest(data.interestRate);
      const doc = {
        ...data,
        interestMin: min,
        interestMax: max,
        minAmountNumeric: parseAmount(data.minAmount),
        maxAmountNumeric: parseAmount(data.maxAmount),
        location: data.location || [data.area, data.city].filter(Boolean).join(', '),
      };
      const item = await Finance.create(doc);
      created.push(item);
    }
    console.log(`Seeded ${created.length} finance services successfully`);

    const count = await Finance.countDocuments();
    console.log(`Total finance services in DB: ${count}`);

    await mongoose.disconnect();
    console.log('Done. Disconnected from MongoDB.');
    process.exit(0);
  } catch (err) {
    console.error('Seed failed:', err.message);
    process.exit(1);
  }
}

seed();
