require('dotenv').config({ path: require('path').join(__dirname, '..', '.env') });
const mongoose = require('mongoose');
const Finance = require('../modules/finance/model');

function parseAmount(value) {
  if (value == null || value === '') return 0;
  const cleaned = String(value).replace(/[₹,\s]/g, '');
  if (cleaned === '' || /^N\/A$/i.test(cleaned) || /^Varies$/i.test(cleaned)) return 0;
  const match = cleaned.match(/^0*(\d+)/);
  if (!match) return 0;
  const num = parseFloat(match[1]);
  return isNaN(num) ? 0 : num;
}

function parseInterest(value) {
  if (value == null || value === '') return { min: 0, max: 0 };
  const cleaned = String(value).replace(/%/g, '').trim();
  if (/^N\/A$/i.test(cleaned) || /^Varies$/i.test(cleaned)) return { min: 0, max: 0 };
  const parts = cleaned.split(/[–-]/).map((p) => parseFloat(p.trim()));
  const nums = parts.filter((n) => !isNaN(n));
  if (nums.length === 0) return { min: 0, max: 0 };
  return { min: nums[0], max: nums.length > 1 ? nums[nums.length - 1] : nums[0] };
}

const base = {
  city: 'bengaluru',
  status: 'active',
  featured: false,
};

const services = [
  {
    ...base,
    serviceName: '100% Home Loan @7% — No CIBIL, No ITR',
    category: 'Home Loans',
    companyName: 'OneVishwam Home Finance',
    providerType: 'Financial Institution',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/HDFC_Logo.svg/1200px-HDFC_Logo.svg.png',
    banner: 'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=1600',
    interestRate: '7%',
    minAmount: '₹5,00,000',
    maxAmount: '₹3,00,00,000',
    tenure: 'Up to 30 years',
    description: 'India\'s most aggressive home loan — 100% funding without CIBIL score or Income Tax Returns. Maximum funding up to ₹3 Crore with tenure up to 30 years. Instant approval for salaried and self-employed professionals.',
    eligibility: ['Salaried / Self-employed / Professionals', 'Age: 21 – 70 years', 'Min income: ₹15,000/month', 'No CIBIL required', 'No ITR required'],
    documentsRequired: ['Aadhaar Card', 'PAN Card', 'Address Proof', 'Property Documents (if finalized)', 'Photo'],
    processingTime: '24 – 48 hours',
    features: ['100% property value funding', 'No CIBIL check', 'No Income Tax Return required', 'Maximum ₹3 Crore', '30-year tenure', 'Instant provisional approval', 'Zero prepayment penalty', 'Balance transfer available'],
    area: 'Indiranagar',
    pincode: '560038',
    contactPhone: '93648 62542',
    contactEmail: 'ceo@onevishwam.com',
    serviceMode: 'Both',
    postedBy: 'Bank',
    availability: 'Available Now',
    featured: true,
  },
  {
    ...base,
    serviceName: 'New Jewellery Purchase Loan — Up to ₹20 Lakhs @5% (Combo Only)',
    category: 'Gold Loans',
    companyName: 'OneVishwam Jewellery Finance',
    providerType: 'Financial Institution',
    logo: '',
    banner: 'https://images.pexels.com/photos/264548/pexels-photo-264548.jpeg?auto=compress&cs=tinysrgb&w=1600',
    interestRate: '5%',
    minAmount: '₹1,00,000',
    maxAmount: '₹20,00,000',
    tenure: 'Up to 5 years',
    description: 'Exclusive new jewellery purchase loan at ultra-low 5% interest — combo offer only. Buy gold, diamond, platinum, or silver jewellery from partner showrooms. Up to ₹20 Lakhs with 5-year tenure. Zero processing fees.',
    eligibility: ['Individuals above 18 years', 'KYC compliant', 'Purchase from partner jewellers only', 'Combo with existing loan optional'],
    documentsRequired: ['Aadhaar Card', 'PAN Card', 'Address Proof', 'Jewellery Quotation from Partner Showroom', 'Photo'],
    processingTime: 'Same day approval',
    features: ['5% fixed interest rate', 'Up to ₹20 Lakhs', '5-year flexible tenure', 'Combo offer with existing loans', 'Zero processing fees', 'Partner showroom network', 'Instant disbursal to jeweller', 'No hidden charges'],
    area: 'Commercial Street',
    pincode: '560001',
    contactPhone: '1800-123-4568',
    contactEmail: 'jewellery@onevishwam.com',
    serviceMode: 'Both',
    postedBy: 'Financial Consultant',
    availability: 'Available Now',
    featured: true,
  },
  {
    ...base,
    serviceName: 'Old Jewellery Loan — Up to ₹10 Lakhs @5% p.a. (Combo + Takeover)',
    category: 'Gold Loans',
    companyName: 'OneVishwam Jewellery Finance',
    providerType: 'Financial Institution',
    logo: '',
    banner: 'https://images.pexels.com/photos/694740/pexels-photo-694740.jpeg?auto=compress&cs=tinysrgb&w=1600',
    interestRate: '5%',
    minAmount: '₹50,000',
    maxAmount: '₹10,00,000',
    tenure: 'Up to 3 years',
    description: 'Pledge your old gold/diamond jewellery and get up to ₹10 Lakhs at just 5% p.a. Combo loan option available plus takeover of existing high-interest gold loans. Free valuation, instant cash, secure locker.',
    eligibility: ['Individuals above 18 years', 'Own gold/diamond jewellery', 'Valid ID proof', 'Existing gold loan takeover welcome'],
    documentsRequired: ['Aadhaar Card', 'PAN Card', 'Gold Ornaments/Coins for Valuation', 'Existing Loan Statement (for takeover)'],
    processingTime: '30 minutes — instant cash',
    features: ['5% p.a. — industry lowest', 'Up to ₹10 Lakhs', 'Combo loan option', 'Existing loan takeover', 'Free doorstep valuation', 'Secure bank-grade lockers', 'Flexible repayment', 'No prepayment charges'],
    area: 'Jayanagar',
    pincode: '560011',
    contactPhone: '1800-123-4569',
    contactEmail: 'goldloan@onevishwam.com',
    serviceMode: 'Both',
    postedBy: 'Bank',
    availability: 'Available Now',
    featured: true,
  },
  {
    ...base,
    serviceName: 'Renewable MSME Trade Finance — Up to ₹10 Crore @7% with Insurance',
    category: 'Business Loans',
    companyName: 'OneVishwam Trade Finance',
    providerType: 'Financial Institution',
    logo: '',
    banner: 'https://images.pexels.com/photos/5648102/pexels-photo-5648102.jpeg?auto=compress&cs=tinysrgb&w=1600',
    interestRate: '7%',
    minAmount: '₹10,00,000',
    maxAmount: '₹10,00,00,000',
    tenure: 'Renewable annually (1 year cycles)',
    description: 'Revolving trade finance facility for MSMEs — up to ₹10 Crore at 7% with comprehensive trade credit insurance coverage. Renewable annually, supports working capital, purchase orders, invoice discounting, and export finance.',
    eligibility: ['MSME registered (Udyam/GST)', 'Business vintage: 2+ years', 'Annual turnover: ₹50L+', 'Clean banking track record'],
    documentsRequired: ['Udyam Registration', 'GST Returns (12 months)', 'Bank Statements (12 months)', 'Audited Financials (2 years)', 'KYC of Directors/Partners', 'Trade References'],
    processingTime: '5 – 7 working days',
    features: ['Up to ₹10 Crore revolving limit', '7% fixed rate with insurance', 'Annual renewable facility', 'Trade credit insurance included', 'Invoice discounting', 'Purchase order financing', 'Export/import finance', 'Digital dashboard for limit utilization'],
    area: 'MG Road',
    pincode: '560001',
    contactPhone: '1800-123-4570',
    contactEmail: 'msme@onevishwam.com',
    serviceMode: 'Both',
    postedBy: 'Bank',
    availability: 'Available Now',
    featured: true,
  },
  {
    ...base,
    serviceName: 'Renewable Business Loan — Up to ₹50 Crore @8%',
    category: 'Business Loans',
    companyName: 'OneVishwam Corporate Finance',
    providerType: 'Financial Institution',
    logo: '',
    banner: 'https://images.pexels.com/photos/3183197/pexels-photo-3183197.jpeg?auto=compress&cs=tinysrgb&w=1600',
    interestRate: '8%',
    minAmount: '₹50,00,000',
    maxAmount: '₹50,00,00,000',
    tenure: 'Renewable annually (3–5 year cycles)',
    description: 'Large-ticket renewable business loan facility for established corporates and high-growth enterprises. Up to ₹50 Crore at 8% with flexible drawdown and annual renewal. Ideal for expansion, acquisitions, and capex.',
    eligibility: ['Corporate / LLP / Partnership', 'Business vintage: 3+ years', 'Net worth: ₹10 Cr+', 'Profitable for 2+ consecutive years', 'Credit rating: BBB+ or equivalent'],
    documentsRequired: ['Certificate of Incorporation', 'Audited Financials (3 years)', 'IT Returns (3 years)', 'Bank Statements (12 months)', 'Credit Rating Letter', 'Board Resolution', 'KYC of Authorized Signatories'],
    processingTime: '10 – 15 working days',
    features: ['Up to ₹50 Crore', '8% competitive rate', 'Multi-year renewable', 'Flexible drawdown/repayment', 'No end-use restriction', 'Syndication support', 'Relationship manager assigned', 'Digital limit management'],
    area: 'Koramangala',
    pincode: '560034',
    contactPhone: '1800-123-4571',
    contactEmail: 'corporate@onevishwam.com',
    serviceMode: 'Both',
    postedBy: 'Bank',
    availability: 'Available Now',
    featured: true,
  },
  {
    ...base,
    serviceName: 'Renewable Overdraft Facilities — Up to ₹20 Crore @7.5%',
    category: 'Business Loans',
    companyName: 'OneVishwam Working Capital',
    providerType: 'Financial Institution',
    logo: '',
    banner: 'https://images.pexels.com/photos/4386366/pexels-photo-4386366.jpeg?auto=compress&cs=tinysrgb&w=1600',
    interestRate: '7.5%',
    minAmount: '₹25,00,000',
    maxAmount: '₹20,00,00,000',
    tenure: 'Renewable annually',
    description: 'Revolving overdraft facility for working capital management — up to ₹20 Crore at 7.5%. Pay interest only on utilized amount. Annual renewal with limit enhancement based on performance. Digital access with real-time monitoring.',
    eligibility: ['Business vintage: 2+ years', 'Annual turnover: ₹1 Cr+', 'Positive net worth', 'Regular banking relationship'],
    documentsRequired: ['Business Registration', 'GST Returns (12 months)', 'Bank Statements (12 months)', 'Financial Projections', 'Stock/Receivables Statement', 'KYC of Directors'],
    processingTime: '7 – 10 working days',
    features: ['Up to ₹20 Crore OD limit', '7.5% on utilized amount only', 'Annual renewable', 'Interest only on usage', 'Digital real-time monitoring', 'Auto-renewal on performance', 'Limit enhancement on review', 'No commitment charges'],
    area: 'Whitefield',
    pincode: '560066',
    contactPhone: '1800-123-4572',
    contactEmail: 'od@onevishwam.com',
    serviceMode: 'Both',
    postedBy: 'Bank',
    availability: 'Available Now',
    featured: true,
  },
  {
    ...base,
    serviceName: 'NPA Takeover Loans — Up to ₹5 Crore @7% (Combo Only)',
    category: 'Business Loans',
    companyName: 'OneVishwam Asset Resolution',
    providerType: 'Financial Institution',
    logo: '',
    banner: 'https://images.pexels.com/photos/4474387/pexels-photo-4474387.jpeg?auto=compress&cs=tinysrgb&w=1600',
    interestRate: '7%',
    minAmount: '₹25,00,000',
    maxAmount: '₹5,00,00,000',
    tenure: '3 – 7 years',
    description: 'Specialized NPA/stressed asset takeover program — up to ₹5 Crore at 7% exclusively as combo loans. We acquire your existing high-cost debt from banks/NBFCs and restructure at affordable rates. Requires viable business plan and collateral.',
    eligibility: ['Existing NPA/stressed account', 'Viable business with turnaround potential', 'Tangible collateral available', 'Promoter commitment for equity infusion', 'Combo with fresh funding mandatory'],
    documentsRequired: ['NPA Classification Letter', 'Outstanding Statements', 'Valuation Reports', 'Turnaround Business Plan', 'Promoter KYC & Net Worth', 'Collateral Documents', 'Forensic Audit (if applicable)'],
    processingTime: '15 – 21 working days',
    features: ['Up to ₹5 Crore takeover', '7% restructured rate', 'Combo with fresh funding', 'Flexible restructuring', 'Moratorium period available', 'Equity participation optional', 'ARCI/DRT settlement support', 'Dedicated resolution team'],
    area: 'Malleshwaram',
    pincode: '560003',
    contactPhone: '1800-123-4573',
    contactEmail: 'npa@onevishwam.com',
    serviceMode: 'Offline',
    postedBy: 'Financial Consultant',
    availability: 'By Application',
    featured: true,
  },
  {
    ...base,
    serviceName: 'Property Purchase / Development Loan for Builders — Up to ₹100 Crore @9%',
    category: 'Home Loans',
    companyName: 'OneVishwam Developer Finance',
    providerType: 'Financial Institution',
    logo: '',
    banner: 'https://images.pexels.com/photos/159306/construction-site-build-construction-work-159306.jpeg?auto=compress&cs=tinysrgb&w=1600',
    interestRate: '9%',
    minAmount: '₹1,00,00,000',
    maxAmount: '₹100,00,00,000',
    tenure: '2 – 5 years (construction-linked)',
    description: 'Mega construction finance for reputed builders and developers — up to ₹100 Crore at 9%. Stage-wise disbursement linked to RERA-approved project milestones. Covers land acquisition, construction, and working capital.',
    eligibility: ['Registered Builder/Developer (RERA)', 'Track record: 3+ completed projects', 'Net worth: ₹25 Cr+', 'Clear land titles with approvals', 'Pre-sales: 30%+ of inventory'],
    documentsRequired: ['RERA Registration', 'Approved Building Plans', 'Land Title & Search Reports', 'Project Cost Breakdown', 'Cash Flow Projections', 'Pre-sale Agreements', 'Audited Financials (3 years)', 'KYC of Directors/Promoters'],
    processingTime: '21 – 30 working days',
    features: ['Up to ₹100 Crore', '9% competitive rate', 'Construction-linked disbursement', 'RERA-compliant escrow', 'Land + construction funding', 'Working capital carve-out', 'No prepayment on sale receipts', 'Dedicated project monitoring'],
    area: 'Sarjapur Road',
    pincode: '560035',
    contactPhone: '1800-123-4574',
    contactEmail: 'developers@onevishwam.com',
    serviceMode: 'Both',
    postedBy: 'Bank',
    availability: 'Available Now',
    featured: true,
  },
  {
    ...base,
    serviceName: 'Automobile Loans — Up to ₹20 Lakhs @8%',
    category: 'Vehicle Loans',
    companyName: 'OneVishwam Auto Finance',
    providerType: 'Financial Institution',
    logo: '',
    banner: 'https://images.pexels.com/photos/170811/pexels-photo-170811.jpeg?auto=compress&cs=tinysrgb&w=1600',
    interestRate: '8%',
    minAmount: '₹2,00,000',
    maxAmount: '₹20,00,000',
    tenure: '1 – 7 years',
    description: 'New and pre-owned vehicle financing up to ₹20 Lakhs at 8%. Cars, SUVs, EVs, two-wheelers, and commercial vehicles. Zero down payment options, insurance bundled, instant approval.',
    eligibility: ['Salaried / Self-employed', 'Age: 21 – 65 years', 'Min income: ₹20,000/month', 'CIBIL: 650+ (flexible for combo)'],
    documentsRequired: ['Aadhaar Card', 'PAN Card', 'Income Proof', 'Vehicle Quotation/Invoice', 'Bank Statements (3 months)', 'Address Proof'],
    processingTime: '24 hours',
    features: ['Up to ₹20 Lakhs', '8% fixed rate', 'New & used vehicles', 'EVs & commercial vehicles', 'Zero down payment', 'Insurance bundled', '7-year max tenure', 'Part-exchange facility'],
    area: 'BTM Layout',
    pincode: '560076',
    contactPhone: '1800-123-4575',
    contactEmail: 'auto@onevishwam.com',
    serviceMode: 'Both',
    postedBy: 'Bank',
    availability: 'Available Now',
    featured: true,
  },
  {
    ...base,
    serviceName: 'Equipment Loans (All Types) — Up to ₹10 Crore @7% p.a.',
    category: 'Business Loans',
    companyName: 'OneVishwam Equipment Finance',
    providerType: 'Financial Institution',
    logo: '',
    banner: 'https://images.pexels.com/photos/3735769/pexels-photo-3735769.jpeg?auto=compress&cs=tinysrgb&w=1600',
    interestRate: '7%',
    minAmount: '₹5,00,000',
    maxAmount: '₹10,00,00,000',
    tenure: '3 – 10 years',
    description: 'Comprehensive equipment and machinery financing up to ₹10 Crore at 7%. Covers medical equipment, construction machinery, industrial plants, IT hardware, agricultural machinery, and renewable energy assets. 100% financing available.',
    eligibility: ['Business vintage: 2+ years', 'Equipment from approved vendors', 'Positive cash flows', 'Equipment as primary collateral'],
    documentsRequired: ['Business Registration', 'Equipment Quotation/Proforma', 'Vendor Credentials', 'Financials (2 years)', 'Bank Statements (6 months)', 'KYC of Directors', 'Technical Specifications'],
    processingTime: '7 – 10 working days',
    features: ['Up to ₹10 Crore', '7% p.a. rate', 'All equipment types', 'Medical, construction, industrial, IT, agri, solar', 'Up to 100% financing', '10-year tenure', 'Tax benefits on depreciation', 'Vendor payment direct'],
    area: 'Peenya Industrial Area',
    pincode: '560058',
    contactPhone: '1800-123-4576',
    contactEmail: 'equipment@onevishwam.com',
    serviceMode: 'Both',
    postedBy: 'Bank',
    availability: 'Available Now',
    featured: true,
  },
  {
    ...base,
    serviceName: 'Barter Finance — Trade Goods/Services for Funding',
    category: 'Other Financial Services',
    companyName: 'OneVishwam Barter Exchange',
    providerType: 'Financial Institution',
    logo: '',
    banner: 'https://images.pexels.com/photos/6802048/pexels-photo-6802048.jpeg?auto=compress&cs=tinysrgb&w=1600',
    interestRate: '0% (Value Exchange)',
    minAmount: '₹10,00,000',
    maxAmount: '₹5,00,00,000',
    tenure: 'As per agreement',
    description: 'Innovative barter finance — convert your unsold inventory, excess capacity, or services into working capital. Trade goods/services on our platform and receive funding or credit without cash interest. Zero interest, value-for-value exchange.',
    eligibility: ['Business with tradable inventory/services', 'Verified quality standards', 'Minimum ₹10L annual trade volume'],
    documentsRequired: ['Business Registration', 'Inventory/Service Catalogue', 'Quality Certifications', 'Trade References', 'KYC of Partners'],
    processingTime: '10 – 15 working days',
    features: ['Zero interest — pure value exchange', 'Unsold inventory monetization', 'Service capacity utilization', 'Network of 500+ barter partners', 'Digital trade credits', 'Tax-compliant transactions', 'Working capital without debt', 'Flexible settlement cycles'],
    area: 'Electronic City',
    pincode: '560100',
    contactPhone: '1800-123-4577',
    contactEmail: 'barter@onevishwam.com',
    serviceMode: 'Online',
    postedBy: 'Financial Consultant',
    availability: 'By Application',
    featured: true,
  },
  {
    ...base,
    serviceName: 'Revenue Sharing Loans — Pay from Future Revenues',
    category: 'Other Financial Services',
    companyName: 'OneVishwam Revenue Finance',
    providerType: 'Financial Institution',
    logo: '',
    banner: 'https://images.pexels.com/photos/5830672/pexels-photo-5830672.jpeg?auto=compress&cs=tinysrgb&w=1600',
    interestRate: 'Revenue Share % (No Fixed Interest)',
    minAmount: '₹25,00,000',
    maxAmount: '₹20,00,00,000',
    tenure: '2 – 5 years or till cap',
    description: 'Alternative financing — no fixed EMI, no fixed interest. Repay as a percentage of monthly revenues (3–8%). Cap at 1.5x–2x principal. Ideal for seasonal businesses, SaaS, e-commerce, and high-growth startups with predictable revenue streams.',
    eligibility: ['Recurring revenue model', '12+ months revenue history', 'Monthly revenue: ₹10L+', 'Gross margin: 40%+', 'Clean banking track record'],
    documentsRequired: ['Revenue Reports (12 months)', 'Bank Statements (12 months)', 'Customer Contracts/Subscriptions', 'Unit Economics', 'Growth Projections', 'KYC of Founders/Directors'],
    processingTime: '10 – 14 working days',
    features: ['No fixed interest/EMi', 'Pay % of revenue (3–8%)', 'Cap at 1.5x–2x principal', 'Seasonal-friendly', 'No collateral', 'Founder-friendly', 'Auto-adjusts with revenue', 'Digital revenue tracking'],
    area: 'HSR Layout',
    pincode: '560102',
    contactPhone: '1800-123-4578',
    contactEmail: 'revenue@onevishwam.com',
    serviceMode: 'Both',
    postedBy: 'Financial Consultant',
    availability: 'By Application',
    featured: true,
  },
  {
    ...base,
    serviceName: 'Small Term Trade Finance — Up to ₹5 Crore @8.5%',
    category: 'Other Financial Services',
    companyName: 'OneVishwam Trade Desk',
    providerType: 'Financial Institution',
    logo: '',
    banner: 'https://images.pexels.com/photos/4386366/pexels-photo-4386366.jpeg?auto=compress&cs=tinysrgb&w=1600',
    interestRate: '8.5%',
    minAmount: '₹5,00,000',
    maxAmount: '₹5,00,00,000',
    tenure: '30 – 180 days',
    description: 'Short-term trade finance for import/export, domestic purchase orders, and vendor payments. Up to ₹5 Crore at 8.5% for 30–180 days. LC/SBLC backing, invoice discounting, and supply chain finance. Fast-track for repeat clients.',
    eligibility: ['Importer/Exporter/Trader', 'Valid IEC Code', 'Purchase Order / LC', 'Supplier/Buyer Credentials', 'Business vintage: 1+ years'],
    documentsRequired: ['IEC Certificate', 'Purchase Order / LC', 'Supplier/Buyer KYC', 'Proforma Invoice', 'Insurance Policy', 'KYC of Company', 'Bank Statements (6 months)'],
    processingTime: '48 hours for repeat, 5 days new',
    features: ['Up to ₹5 Crore', '8.5% for 30–180 days', 'LC/SBLC backed', 'Invoice discounting', 'Vendor payment financing', 'Import/export/domestic', 'Fast-track renewals', 'Digital document flow'],
    area: 'Yeshwanthpur',
    pincode: '560022',
    contactPhone: '1800-123-4579',
    contactEmail: 'shortterm@onevishwam.com',
    serviceMode: 'Both',
    postedBy: 'Bank',
    availability: 'Available Now',
    featured: true,
  },
  {
    ...base,
    serviceName: 'Venture Funding — Equity & Venture Debt for Startups',
    category: 'Other Financial Services',
    companyName: 'OneVishwam Ventures',
    providerType: 'Financial Institution',
    logo: '',
    banner: 'https://images.pexels.com/photos/3183197/pexels-photo-3183197.jpeg?auto=compress&cs=tinysrgb&w=1600',
    interestRate: 'Equity / Venture Debt (12–15%)',
    minAmount: '₹50,00,000',
    maxAmount: '₹100,00,00,000',
    tenure: '3 – 7 years (venture debt) / Perpetual (equity)',
    description: 'Early-stage to growth-stage venture funding — equity investment and venture debt for high-potential startups. ₹50L–₹100Cr across SaaS, FinTech, HealthTech, DeepTech, Consumer, and B2B. Strategic value-add beyond capital.',
    eligibility: ['DPIIT Recognized Startup', 'Scalable business model', 'TAM: ₹500Cr+', 'Strong founding team', 'Traction: Revenue/Users/Partnerships'],
    documentsRequired: ['Pitch Deck', 'Financial Model', 'Cap Table', 'IP/Patents', 'Customer References', 'Founder KYC', 'Board Resolution', 'Due Diligence Access'],
    processingTime: '4 – 8 weeks',
    features: ['Equity: ₹50L–₹50Cr', 'Venture Debt: ₹1Cr–₹20Cr @12–15%', 'Strategic mentorship', 'Network of 200+ investors', 'Follow-on funding', 'Exit support', 'Governance lite', 'Sector expertise'],
    area: 'Koramangala',
    pincode: '560034',
    contactPhone: '1800-123-4580',
    contactEmail: 'ventures@onevishwam.com',
    serviceMode: 'Both',
    postedBy: 'Financial Consultant',
    availability: 'By Application',
    featured: true,
  },
];

async function seed() {
  try {
    const uri = process.env.MONGODB_URI || 'mongodb://localhost:27017/onevishwam';
    await mongoose.connect(uri);
    console.log('Connected to MongoDB');

    await Finance.deleteMany({});
    console.log('Cleared existing finance services');

    const created = [];
    for (const data of services) {
      const { min, max } = parseInterest(data.interestRate);
      const doc = {
        ...data,
        interestMin: min,
        interestMax: max,
        minAmountNumeric: parseAmount(data.minAmount),
        maxAmountNumeric: parseAmount(data.maxAmount),
        location: data.location || [data.area, data.city].filter(Boolean).join(', '),
      };
      const item = await Finance.create(doc);
      created.push(item);
    }
    console.log(`Seeded ${created.length} finance services successfully`);

    const count = await Finance.countDocuments();
    console.log(`Total finance services in DB: ${count}`);

    await mongoose.disconnect();
    console.log('Done. Disconnected from MongoDB.');
    process.exit(0);
  } catch (err) {
    console.error('Seed failed:', err.message);
    process.exit(1);
  }
}

seed();